namespace: openstack
name: cloud
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies: {}
repository: git@github.com:coll-test/openstack.cloud.git
documentation: https://github.com/coll-test/openstack.cloud/tree/master/docs
homepage: https://github.com/coll-test/openstack.cloud
issues: https://github.com/coll-test/openstack.cloud/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
